CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  default_language VARCHAR(50) NOT NULL DEFAULT 'English (EN)',
  grid_density VARCHAR(20) NOT NULL DEFAULT 'Comfortable',
  pref_onboarding TINYINT(1) NOT NULL DEFAULT 1,
  pref_product TINYINT(1) NOT NULL DEFAULT 1,
  pref_promotions TINYINT(1) NOT NULL DEFAULT 0,
  pref_brand TINYINT(1) NOT NULL DEFAULT 1,
  pref_newsletter TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(150) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  format VARCHAR(100) NOT NULL,
  variant VARCHAR(20) NOT NULL,
  eyebrow VARCHAR(100),
  headline VARCHAR(255) NOT NULL,
  sub VARCHAR(255),
  cta VARCHAR(100),
  badge VARCHAR(100),
  media_type VARCHAR(10) NOT NULL,
  swatch VARCHAR(255) NOT NULL,
  light TINYINT(1) NOT NULL DEFAULT 0,
  category VARCHAR(100) NOT NULL,
  market VARCHAR(10) NOT NULL,
  language VARCHAR(50) NOT NULL DEFAULT 'English (EN)',
  photo_url VARCHAR(500),
  platforms VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS saved_ads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  ad_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_ad (user_id, ad_id),
  CONSTRAINT fk_saved_ads_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_saved_ads_ad FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS creative_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'New creative',
  size_needed VARCHAR(150),
  needed_by DATE,
  notes TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'Open',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_requests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
