import "dotenv/config";
import bcrypt from "bcryptjs";
import { prisma } from "../lib/prisma.js";

const PLATFORM_OPTIONS = "META,Google,TikTok,LinkedIn";

const ADS = [
  {
    slug: "long-walk-home",
    title: "Long Walk Home",
    format: "Feed 1:1",
    variant: "overlay",
    eyebrow: "Spring drop",
    headline: "Built for the long walk home.",
    sub: null,
    cta: "Shop now",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-b from-neutral-700 via-neutral-800 to-black",
    light: false,
    category: "E-commerce / DTC",
    market: "UK",
    photo: "https://picsum.photos/seed/adplaylist-long-walk-home/800/1000",
    editable: true,
    dominantColor: "Black",
    videoLength: null,
  },
  {
    slug: "members-weekend",
    title: "Members Weekend",
    format: "Poster",
    variant: "overlay",
    eyebrow: null,
    headline: "30% off",
    sub: "Ends Sunday. Members only.",
    cta: null,
    badge: null,
    mediaType: "image",
    swatch: "bg-brand",
    light: false,
    category: "E-commerce / DTC",
    market: "UK",
    photo: null,
    editable: true,
    dominantColor: "Red",
    videoLength: null,
  },
  {
    slug: "season-two",
    title: "Season Two",
    format: "Photo lockup",
    variant: "lockup",
    eyebrow: null,
    headline: "New season, same boots.",
    sub: "Free returns for 60 days",
    cta: null,
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-b from-neutral-400 to-neutral-500",
    light: false,
    category: "E-commerce / DTC",
    market: "UK",
    photo: "https://picsum.photos/seed/adplaylist-season-two/800/600",
    editable: false,
    dominantColor: "Grey",
    videoLength: null,
  },
  {
    slug: "flash-sale",
    title: "Flash Sale",
    format: "Story set",
    variant: "overlay",
    eyebrow: null,
    headline: "Two days. Then it's gone.",
    sub: null,
    cta: null,
    badge: "Story · 9:16",
    mediaType: "image",
    swatch: "bg-neutral-200",
    light: true,
    category: "E-commerce / DTC",
    market: "UK",
    photo: null,
    editable: true,
    dominantColor: "White",
    videoLength: null,
  },
  {
    slug: "six-weeks",
    title: "Six Weeks",
    format: "Bumper 15s",
    variant: "overlay",
    eyebrow: null,
    headline: "Six weeks of rain. One pair.",
    sub: "Bumper · sound off",
    cta: null,
    badge: "0:15",
    mediaType: "video",
    swatch: "bg-gradient-to-br from-neutral-800 to-black",
    light: false,
    category: "E-commerce / DTC",
    market: "UK",
    photo: "https://picsum.photos/seed/adplaylist-six-weeks/800/1000",
    editable: false,
    dominantColor: "Black",
    videoLength: "6–15s",
  },
  {
    slug: "fleur-serum",
    title: "Fleur Serum",
    format: "Feed 1:1",
    variant: "overlay",
    eyebrow: "New formula",
    headline: "Ten drops. One week.",
    sub: null,
    cta: "Try it",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-br from-pink-300 to-rose-400",
    light: false,
    category: "Beauty & Skincare",
    market: "DE",
    photo: "https://picsum.photos/seed/adplaylist-fleur-serum/800/1000",
    editable: true,
    dominantColor: "Pink",
    videoLength: null,
  },
  {
    slug: "night-routine",
    title: "Night Routine",
    format: "Story set",
    variant: "overlay",
    eyebrow: null,
    headline: "Three steps before bed.",
    sub: null,
    cta: null,
    badge: "Story · 9:16",
    mediaType: "image",
    swatch: "bg-gradient-to-b from-violet-400 to-indigo-600",
    light: false,
    category: "Beauty & Skincare",
    market: "DE",
    photo: "https://picsum.photos/seed/adplaylist-night-routine/800/1000",
    editable: true,
    dominantColor: "Purple",
    videoLength: null,
  },
  {
    slug: "glow-test",
    title: "Glow Test",
    format: "Reel 30s",
    variant: "overlay",
    eyebrow: null,
    headline: "We tested it for 30 nights.",
    sub: "Reel · captions on",
    cta: null,
    badge: "0:30",
    mediaType: "video",
    swatch: "bg-gradient-to-br from-fuchsia-300 to-pink-500",
    light: false,
    category: "Beauty & Skincare",
    market: "DE",
    photo: "https://picsum.photos/seed/adplaylist-glow-test/800/1000",
    editable: true,
    dominantColor: "Pink",
    videoLength: "15–30s",
  },
  {
    slug: "refill-club",
    title: "Refill Club",
    format: "Poster",
    variant: "overlay",
    eyebrow: null,
    headline: "Refill & save",
    sub: "Two bottles, one price.",
    cta: null,
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-br from-emerald-500 to-green-700",
    light: false,
    category: "Beauty & Skincare",
    market: "NL",
    photo: null,
    editable: true,
    dominantColor: "Green",
    videoLength: null,
  },
  {
    slug: "northbank-savings",
    title: "Northbank Savings",
    format: "Feed 1:1",
    variant: "overlay",
    eyebrow: "Fixed rate",
    headline: "4.2% and it stays there.",
    sub: null,
    cta: "Open account",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-b from-slate-700 to-slate-900",
    light: false,
    category: "Finance & Fintech",
    market: "UK",
    photo: "https://picsum.photos/seed/adplaylist-northbank-savings/800/1000",
    editable: true,
    dominantColor: "Blue",
    videoLength: null,
  },
  {
    slug: "rift-nine",
    title: "Rift Nine",
    format: "Launch 1:1",
    variant: "overlay",
    eyebrow: "Season nine",
    headline: "The rift opens tonight.",
    sub: null,
    cta: "Play free",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-br from-purple-800 via-purple-900 to-black",
    light: false,
    category: "Gaming & Creator",
    market: "US",
    photo: "https://picsum.photos/seed/adplaylist-rift-nine/800/1000",
    editable: true,
    dominantColor: "Purple",
    videoLength: null,
  },
  {
    slug: "vitalis-sleep",
    title: "Vitalis Sleep",
    format: "Feed 1:1",
    variant: "overlay",
    eyebrow: "Sleep study",
    headline: "Asleep in nineteen minutes.",
    sub: null,
    cta: "See the study",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-b from-sky-700 to-blue-950",
    light: false,
    category: "Health & Fitness",
    market: "US",
    photo: "https://picsum.photos/seed/adplaylist-vitalis-sleep/800/1000",
    editable: true,
    dominantColor: "Blue",
    videoLength: null,
  },
  {
    slug: "cadence-launch",
    title: "Cadence Launch",
    format: "Feed 1:1",
    variant: "overlay",
    eyebrow: "Now shipping",
    headline: "Plan the quarter in an hour.",
    sub: null,
    cta: "Book a demo",
    badge: null,
    mediaType: "image",
    swatch: "bg-gradient-to-br from-teal-600 to-cyan-800",
    light: false,
    category: "SaaS & Tech",
    market: "US",
    photo: "https://picsum.photos/seed/adplaylist-cadence-launch/800/1000",
    editable: true,
    dominantColor: "Black",
    videoLength: null,
  },
  {
    slug: "clean-shelf",
    title: "Clean Shelf",
    format: "Photo lockup",
    variant: "lockup",
    eyebrow: null,
    headline: "Nothing you can't pronounce.",
    sub: "Vegan, refillable, unscented",
    cta: null,
    badge: null,
    mediaType: "image",
    swatch: "bg-neutral-300",
    light: false,
    category: "Beauty & Skincare",
    market: "NL",
    photo: "https://picsum.photos/seed/adplaylist-clean-shelf/800/600",
    editable: false,
    dominantColor: "Grey",
    videoLength: null,
  },
];

async function seed() {
  console.log("Seeding database...");

  const passwordHash = await bcrypt.hash("password123", 10);
  const user = await prisma.user.upsert({
    where: { email: "anna.smith@atlasmedia.co" },
    update: { fullName: "Anna Smith", role: "admin" },
    create: {
      email: "anna.smith@atlasmedia.co",
      passwordHash,
      fullName: "Anna Smith",
      role: "admin",
    },
  });

  for (const ad of ADS) {
    const data = {
      title: ad.title,
      format: ad.format,
      variant: ad.variant,
      eyebrow: ad.eyebrow,
      headline: ad.headline,
      sub: ad.sub,
      cta: ad.cta,
      badge: ad.badge,
      mediaType: ad.mediaType,
      swatch: ad.swatch,
      light: ad.light,
      category: ad.category,
      market: ad.market,
      language: "English (EN)",
      photoUrl: ad.photo,
      platforms: PLATFORM_OPTIONS,
      editable: ad.editable,
      dominantColor: ad.dominantColor,
      videoLength: ad.videoLength,
    };
    await prisma.ad.upsert({
      where: { slug: ad.slug },
      update: data,
      create: { slug: ad.slug, ...data },
    });
  }

  const membersWeekend = await prisma.ad.findUniqueOrThrow({
    where: { slug: "members-weekend" },
  });
  await prisma.savedAd.upsert({
    where: { userId_adId: { userId: user.id, adId: membersWeekend.id } },
    update: {},
    create: { userId: user.id, adId: membersWeekend.id },
  });

  const requestCount = await prisma.creativeRequest.count({
    where: { userId: user.id },
  });
  if (requestCount === 0) {
    await prisma.creativeRequest.createMany({
      data: [
        {
          userId: user.id,
          title: "Long Walk Home in 728 x 90",
          type: "New size",
          sizeNeeded: "728 x 90",
          neededBy: new Date("2026-09-18"),
          status: "In design",
        },
        {
          userId: user.id,
          title: "Members Weekend — Swedish copy",
          type: "Localisation",
          neededBy: new Date("2026-09-22"),
          status: "Awaiting brief",
        },
        {
          userId: user.id,
          title: "Autumn boot range — story set",
          type: "New creative",
          sizeNeeded: "1080 x 1920",
          neededBy: new Date("2026-09-30"),
          status: "In review",
        },
      ],
    });
  }

  // A delivered example so the Requests page's Delivered tab has something
  // real to render (a request that resulted in an existing library ad),
  // added separately/idempotently since it postdates the block above.
  const delivered = await prisma.creativeRequest.findFirst({
    where: { userId: user.id, title: "Long Walk Home — hero banner" },
  });
  if (!delivered) {
    const heroAd = await prisma.ad.findUniqueOrThrow({
      where: { slug: "long-walk-home" },
    });
    await prisma.creativeRequest.create({
      data: {
        userId: user.id,
        title: "Long Walk Home — hero banner",
        type: "New creative",
        sizeNeeded: "1080 x 1080",
        neededBy: new Date("2026-09-05"),
        status: "Delivered",
        adId: heroAd.id,
      },
    });
  }

  console.log(`Seeded 1 user and ${ADS.length} ads.`);
  await prisma.$disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
